### ISSUE TITLE
querys seguras

### ISSUE THREAD

**Issue by devCanario** [zZang32/flask-restful-api-crud#1]
Si una query falla no se cierra la query ni la conexion y tienes que reiniciar la app manualmente porque se traba (cuando calculas mal la query o escribes mal) lo de buffered es opcional, me paso a veces al escribir el projecto de find de curso

```py
class DoEvent(Resource):
  def get(self):
      try:
          conn = db.connection()
          query = conn.cursor(buffered=True)
      except:
          return {'error', 'db error'}, 500
      finally:
          query.close()
          conn.close()
```

**Comment by itsangelo92** [comment]
Gracias por el ejemplo y la explicación, ahora en un rato lo rectifico
